# Error Correcting Codes Encoding Study

The goal of this study is to understand options to the popular one-hot encoding. There are many sides to each story (no, not only two), on those sides are: 

- I never liked one-hot encoding (and is been more than a decade since I first used it, so the disgust might never go out);
- I don't like how neural networks are treated and should always be end to end learning (no they should not, they should be more complex architectures, many already in research literature)
- There are priors 
- Each type of input should  (and HAS in nature) its own priors, which are adapted to *facilitate* the learning, no we should not do everyhting inside a NN, we should give as input something that has priors that facilitate learning (and might or might not later save processing power during operations)


On the priors, many have already shown good results, the most remarcable prior are: Convolutional Neural Networks, MAC Networks, LSTMs, others are more subtle, like (remember citation here ...) adding a coordinate system to the input image as an (or many) extra channel(s). There are many more that I think are worth exploring and adding to the literature, even if they don't give good results. 
On those priors there are many that we not only know, but also we have specialized hardware that is perfectly adapted
* time and space -> this we can encode and add it as extra channels
* Different transforms (Fourier, Laplace, Wavelets, ...)
* spikes (borders in images)
* ....

There is another idea behind the ECCs, is that we usually can 'feel' that something is not right or missing, what about giving NNs a way of having an extra element that would allow for this 'feeling'? 

The idea behind this is that I don't agree with one-hot encoding the way is used today, not because it does not work, but because it imposes a few limits that I don't want to deal with at first

* We know the actual number of values to encode (with words this is not necessary true)
* We have a sample data to train the encoding

This limits us in several ways; for example, for training on a domain, the encoder will depend on that domain only. If there are under-represented values (such as words that don't appear or are new later, or changing domain) this limits the encoding possibliities. A better idea will be to be able to encode everything even if the internal representations have not yet learned to use those simbols.

I want to be able to do a separation ebtween the *possibility*  of representing a value, and the learning of that concept.

The first and biggest limitation of one-hot encoding is that does not allow to represent values that are not accepted.

As some other parts of this study have already focused on integer value representations, arbitrary function representation (although with limitted success on the fourier inspired encodings) this study is more focused on being able to represent correctly all the values of utf-8, basically doing a first binary representation that will be given as input to an OVERFITTED encoder. 

The reasoning behind this is:


* The origin domain is all text
* UTF-8 can represent all text in all languages including some extra elements
* let's use UTF-8 as the origin domain
* Create an encoder that can deal with ANY and ALL input in the origin domain
* the encoded values can later be used

As text should be always correctly reconstructed in the presence of noise, I want to imagine now a Neural Network like a REALLY NOISY channel. For this using (Forward) ECCs is one way of thinking in this medium
Then the tests that I intend to do is:

* Create an autoencoder that OVERFITS to all the data


One idea that I have been dealing with my head for the past 3-4 years is that we are thinking overfitting the wrong way, and we can actually use it well, but we have to learn how.

I think that here is the first time I actually find a way of doing it in a useful way

The idea is to overfit so it generates an smaller encoding vector than the one in the input. Autoencoders are good to do this test.

The other idea is that if the autoencoder can NOT do this, then the encoding ideas that I will try are BAAAD and I should feel BAAAD. In this case ... just go to the drawing table and think of other things.

On the other side, if this works, this means that FINALLY I can go on the next stage, that is building the predictors first basic ones (LSTMs, HMMs, Time Convolutions), then with meta-learning and later with my still too fresh idea on neural databases. 

One interesting thing I want to find out about Error Correcting Codes (ECCs) is if they are actually useful in the output decoding, as they should be adding *explicit* redundancy to the input and also to the output.

The other thing about ECCs is that we can pile them up, for example, one (or many codes) to representa a symbol (for example the value *'€'* ) and then use convolutional or turbo codes for the *temporal* encoding/decoding part, this means that we not only add priors to the intantaneous input, but also to the temporal dimension, which is something I really want to explore (and this should facilitate fixing and correcting "channel errors")

I don't deal here with *erasure* error types, but that is a possibility later.


In [1]:
import numpy as np
import commpy
# import bitarray as ba
import struct
import sys
# import binascii
from bitstring import BitArray, BitStream


In [2]:
sys.byteorder

'little'

In [71]:
c = '€'.encode()

In [72]:
c

b'\xe2\x82\xac'

In [94]:
a = 'a'

AttributeError: 'str' object has no attribute 'hex'

In [99]:
'a'.encode()[0]

97

In [100]:
len(bytearray('a'.encode()))

1

In [5]:
zero = BitArray(b'\x00\x00\x00\x00')
b = BitArray(c)

In [6]:
b

BitArray('0xe282ac')

In [7]:
b.tobytes()

b'\xe2\x82\xac'

In [8]:
int.from_bytes(c, byteorder='big')

14844588

In [9]:
32 - b.len

8

In [10]:
int.from_bytes(c, byteorder='big') >> 1

7422294

In [11]:
for i in range ((32 - b.len)//8):
    b.prepend(b'\x00')

In [12]:
b.len

32

In [13]:
b

BitArray('0x00e282ac')

In [14]:
32 - b.len

0

In [15]:
a = 256
a.bit_length()

9

In [112]:
'€'.encode()[1]

130

In [62]:
# Bit of a whacky hack and for sure not the most efficient one, but it just works for what I want

def prepend_zeros(s, n):
    return '0'* (n - len(s))+s

def get_strbintable(n):
    bl = n.bit_length() - 1  # because n is actually never used
    lines = [ ' '.join(i for i in prepend_zeros("{0:b}".format(l), bl)) for l in range(n)]
    return lines

def get_npbintable(n):
    bins = np.fromstring('\n'.join(get_strbintable(n)), dtype='int32', sep=' ')
    bins = bins.reshape([n, -1])
    return bins
    

Since the entire utf-8 univers is NOT the entire $2^{32}$ domain, but there are limitations explained in [the utf-8 description](https://en.wikipedia.org/wiki/UTF-8)

| Number of bytes | Bits for code point | First code point | Last code point | Byte 1   | Byte 2   | Byte 3   | Byte 4   |
|----------------|--------------------|-----------------|----------------|----------|----------|----------|----------|
| 1              | 7                  | U+0000          | U+007F         | 0xxxxxxx |          |          |          |
| 2              | 11                 | U+0080          | U+07FF         | 110xxxxx | 10xxxxxx |          |          |
| 3              | 16                 | U+0800          | U+FFFF         | 1110xxxx | 10xxxxxx | 10xxxxxx |          |
| 4              | 21                 | U+10000         | U+10FFFF       | 11110xxx | 10xxxxxx | 10xxxxxx | 10xxxxxx |

I'll then compute different table parts and do an append when needed

The thing is that the number of elements in the table should be at most $2^{21}$, I need to create a sort of index that can handle the 4 cases.
It seems I'll have to create 4 different conversion tables.




In [148]:
# this part makes sure to encode as bin
eye4 = np.eye(4)

# code for 7 bits, Byte 1 of utf-8
code_b7 = np.append(np.zeros([2**7, 1]), get_npbintable(2**7), axis=1)

# code for 6 bits, Byte 2 to 4 of utf-8 -> this is going to be used later for all the other values
code_b6 = np.append(np.append(np.ones([2**6, 1]), np.zeros([2**6, 1]), axis=1), 
                    get_npbintable(2**6), axis=1)

# code for 5 bits, Byte 1 of 
code_b5 = np.append(np.append(np.ones([2**5, 2]), np.zeros([2**5, 1]), axis=1), 
                    get_npbintable(2**5), axis=1)

# code for 4 bits, Byte 2 to 4 of utf-8 -> this is going to be used later for all the other values
code_b4 = np.append(np.append(np.ones([2**4, 3]), np.zeros([2**4, 1]), axis=1), 
                    get_npbintable(2**4), axis=1)

# code for 3 bits, Byte 2 to 4 of utf-8 -> this is going to be used later for all the other values
code_b3 = np.append(np.append(np.ones([2**3, 4]), np.zeros([2**3, 1]), axis=1),
                    get_npbintable(2**3), axis=1)

def encode_utf8(l):
    el = l.encode()
    code = np.zeros(36)  # 32 is the size of the input code + 4 of the extra redundancy
    nbytes = len(el)
    # assert( 0<nbytes && nbytes<=4)
    assert(nbytes<=4)
    bin4 = eye4[nbytes-1]  # this adds redundant knowledge about the  part
    # this is ugly but explicit, for the moment is good enough and I can see what is
    code[:4] = bin4
    if nbytes == 1:
        code[4:12] = code_b7[el[0]& 0b01111111 ]
    elif nbytes == 2:
        code[4:12] = code_b5[el[0] & 0b00011111 ]
        code[12:20] = code_b6[el[1] & 0b00111111]
    elif nbytes == 3:
        code[4:12] = code_b4[el[0] & 0b00001111]
        code[12:20] = code_b6[el[1] & 0b00111111]
        code[20:28] = code_b6[el[2] & 0b00111111]
    elif nbytes == 4:
        code[4:12] = code_b3[el[0] & 0b00000111]
        code[12:20] = code_b6[el[1] & 0b00111111]
        code[20:28] = code_b6[el[2] & 0b00111111]
        code[28:36] = code_b6[el[3] & 0b00111111]
    else:
        raise Exception("Bad input, input has to have 1 to 4 input bytes")
    return code


def encode_utf8_ecc(l):
    el = l.encode()
    code = np.zeros(36)  # 32 is the size of the input code + 4 of the extra redundancy
    nbytes = len(el)
    # assert( 0<nbytes && nbytes<=4)
    assert(nbytes<=4)
    bin4 = eye4[nbytes-1]  # this adds redundant knowledge about the  part
    # this is ugly but explicit, for the moment is good enough and I can see what is
    code[:4] = bin4
    if nbytes == 1:
        code[4:12] = code_b7[el[0]& 0b01111111 ]
    elif nbytes == 2:
        code[4:12] = code_b5[el[0] & 0b00011111 ]
        code[12:20] = code_b6[el[1] & 0b00111111]
    elif nbytes == 3:
        code[4:12] = code_b4[el[0] & 0b00001111]
        code[12:20] = code_b6[el[1] & 0b00111111]
        code[20:28] = code_b6[el[2] & 0b00111111]
    elif nbytes == 4:
        code[4:12] = code_b3[el[0] & 0b00000111]
        code[12:20] = code_b6[el[1] & 0b00111111]
        code[20:28] = code_b6[el[2] & 0b00111111]
        code[28:36] = code_b6[el[3] & 0b00111111]
    else:
        raise Exception("Bad input, input has to have 1 to 4 input bytes")
    return code

In [189]:
el = '€'.encode()
code = np.zeros(36)  # 32 is the size of the input code + 4 of the extra redundancy
nbytes = len(el)
bin4 = UTF8Coder.eye4[nbytes]  # this adds redundant knowledge about the  part
# this is ugly but explicit, for the moment is good enough and I can see what is
code[:4] = bin4

In [197]:
el

b'\xe2\x82\xac'

In [193]:
hex(int.from_bytes(el, 'big')) & hex(b'\x00\x00\x00\x00')

TypeError: 'bytes' object cannot be interpreted as an integer

In [192]:
hex(int.from_bytes(el, 'little'))

'0xac82e2'

In [198]:
le = bytearray(el)

In [201]:
le.reverse()

In [204]:
le.

SyntaxError: invalid syntax (<ipython-input-204-edd867f594e4>, line 1)

In [173]:
hex(el) & hex(b'\x00\x00\x00\x00')

TypeError: 'bytes' object cannot be interpreted as an integer

In [154]:
encode_utf8('á')

array([0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [18]:
2**21 # this should be enough to make the entire utf-8 encoding ... and much more

2097152

In [19]:
%%time

tt10 = get_npbintable(2**21)

CPU times: user 3.84 s, sys: 97.6 ms, total: 3.93 s
Wall time: 3.93 s


In [20]:
tt10[101]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1],
      dtype=uint16)

In [105]:
# Dense binary input codes

# code for 7 bits, Byte 1 of utf-8
code_b7 = get_npbintable(2**7)
t_zeros = np.zeros([2**7, 1])
code_b7 = np.append(t_zeros, code_b7, axis=1)

# code for 6 bits, Byte 2 to 4 of utf-8 -> this is going to be used later for all the other values
code_b6 = get_npbintable(2**6)
t_b6 = np.append(np.ones([2**6, 1]), np.zeros([2**6, 1]), axis=1)
code_b6 = np.append(t_b6, code_b6, axis=1)

# code for 5 bits, Byte 1 of 
code_b5 = get_npbintable(2**5)
t_b5 = np.append(np.ones([2**5, 2]), np.zeros([2**5, 1]), axis=1)
code_b5 = np.append(t_b5, code_b5, axis=1)

# code for 6 bits, Byte 2 to 4 of utf-8 -> this is going to be used later for all the other values
code_b4 = get_npbintable(2**4)
t_b4 = np.append(np.ones([2**4, 3]), np.zeros([2**4, 1]), axis=1)
code_b4 = np.append(t_b4, code_b4, axis=1)

# code for 6 bits, Byte 2 to 4 of utf-8 -> this is going to be used later for all the other values
code_b3 = get_npbintable(2**3)
t_b3 = np.append(np.ones([2**3, 4]), np.zeros([2**3, 1]), axis=1)
code_b3 = np.append(t_b3, code_b3, axis=1)

# 4 bits
b4 = get_npbintable(2**4)
eye4 = np.eye(4)

In [106]:
eye4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.eye(16)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In fact ... it seems that I can just chunk the utf-8 value in chunks and do one-hot per different parts:
- there are only 4 segment ranges, that can be coded in one-hot also add there either hamming or other ECC
- the largest value is for 7 bits -> 128 values
- the others contain 6 bits -> 64 values
The prefix of each can be taken away and replaced by the initial one-hot

So a complete code would be
$ 4 + 128 + 64 + 64 + 64 = 324 $

plus the ECC parity bits

Instead of having dimension 1,112,064 to encode any utf-8 value.

The encoder is  much simpler than I thought for this case, later I can add ECC for each, knowing that there is only one active bit in each row, this makes the task easier.

This embedding can stil be reduced but should be sparse enough already to make a good input

In [23]:
4 + 128 + 64 + 64 + 64 

324

In [70]:
c

12

In [24]:
np.fromstring('0 0 1 0 1 0 0 1', dtype=bool, sep=' ')

array([False, False,  True, False,  True, False, False,  True])

In [25]:
np.fromstring('00101001', dtype=bool)  # there seems to be an issue here on numpy ...

/home/leo/DeepLearning/venv3/lib/python3.5/site-packages/ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([ True,  True,  True,  True,  True,  True,  True,  True])

In [48]:
np.fromstring('0 0 1 0 1 0 0 1', dtype=int, sep=' ')

array([0, 0, 1, 0, 1, 0, 0, 1])

In [27]:
bins = np.fromstring('\n'.join(get_strbintable(16)), dtype='<H', sep=' ')

In [28]:
bins.reshape([16,-1])

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 1]], dtype=uint16)

In [29]:
np.array(get_strbintable(16))

array(['0 0 0 0', '0 0 0 1', '0 0 1 0', '0 0 1 1', '0 1 0 0', '0 1 0 1',
       '0 1 1 0', '0 1 1 1', '1 0 0 0', '1 0 0 1', '1 0 1 0', '1 0 1 1',
       '1 1 0 0', '1 1 0 1', '1 1 1 0', '1 1 1 1'], dtype='<U7')


I tried to do some things about the first part of the code, turning bytes to a numpy array, but seems that the most efficient way would be a table (numpy 2d array that has as index the int value of the input and there the array in that position is the binary code, this can already include the first pass to make a one hot of every N bits (maybe every 4, so there are not so many initial values ), this matrix could already have pre-computed the ECC ...

For the ECC, I stil don't decide if making it by chunks of input bits, or by all the values, I guess that by all should do, but maybe is easier to compute them reshaping the input arrays to the code in use (example for Golay [24,12,8] will do for every 12 input bits) 

The idea is to not completely get rid of one-hot encoding, but to limit it to parts of the input vector code restricting the size of the domain

In [30]:
# number of parameters for a one-hot by chunks encoding:
chunk_sizes = [4, 5, 6, 8, 12]
n_params = []
for c in chunk_sizes:
    n_params.append((c, (32 // c) * 2**c))

In [31]:
n_params

[(4, 128), (5, 192), (6, 320), (8, 1024), (12, 8192)]

Maybe for my tests up to chunks of size 6 should be acceptable (I still need to add the next ECC)

The next code can be:
- Repetition (x3)
- Hamming
- Golay
- Reed Solomon
- Latin Square 
- AN Correcting

Here some thoughts about the codes:

Repetition: this has the disadvantage of giving a redundancy that is quite obvious besides the low power of reconstruction of catastrofic errors. Just repeating does not necessarilly adds to a neural network another perspective at the input. Might be worth trying, but for the moment I'm not interested in it.

Hamming: it can correct one error (Hamming 7,4), adding 3 out of 4 bits. With an extra bit it can detect up to 2 errors with an extra parity bit.

Golay: might serve well enough for my first tests as it ads not too much overhead (duplicates the number of elements) for an interesting error correction (up to 3 bits from each 12, so one fourth).


There is one difference in the focus from this analysis and telecomunications (or any other domain with noisy channel), here I'm interested not in the code Rate (ammount of information sent vs ammount of actual bits sent) but in giving as input to the NN some form of non necessary evident redundancy that it could use, and having more ways to correct the output if a single mistake is made during the output extrapolation, I want ot check this part.

Thinking a bit more about auto-encoders, it might not be the best idea to start there as it might not give any useful information ... I still have to try some things, might give it a try if it is quick enough to build it once I have the input code.


For efficiency what I will do is build from the beginning the encoding table, for the decoding, I still need to think it thorugh.


In [36]:
import torch

emd = torch.nn.Embedding(2**10, 300)

In [37]:
model_parameters = filter(lambda p: p.requires_grad, emd.parameters())
params = sum([np.prod(p.size()) for p in model_parameters])


In [38]:
params

307200

In [40]:
# from https://discuss.pytorch.org/t/how-do-i-check-the-number-of-parameters-of-a-model/4325/7
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

In [41]:
count_parameters(emd)

307200

The embedding layer is a fully connected layer ... this means a LOT of parameters

To be able to do an effective one-hot of all utf-8 would be:

In [67]:
for i in [50,100,200,300]:
    print(i, 1112064 * i)

50 55603200
100 111206400
200 222412800
300 333619200


Which means I don't want to train that layer ... it would not even fit in my GPU

There is another thing, the embedding layer learns from the sample input, this means that it will ignore all values that don't appear or are underrepresented (a know issue). My goal is to deal with this with meta-learning techniques, but always being able to keep adding new inputs.

So I want a few encoders to try:

- chunked one-hot + hamming error correction of the first element
- binary like encoding only (will be done per byte to avoid making a table that is too big)
- binary like encoding with ECCs
- binary like encoding but added one-hot by each 4 bits (total 16 * 8 -> 128 bits)
- binary like encoding but added one-hot by each (4|12) bits plus ECC (total (16 * 8) + overload), hamming=224, golay=256




In [83]:
128  + 32*3

224