# Simplified Sinusoidal encodings

What if I'm complicating my life too much with the desire of making a linear decoding and I should directly do with sinusoidals?

For each time scale I can directly do an INT division, get only the reminder and use that, I can do a few sin/cos phased elements and this should be enough to reconstruct the initial signal .... lets see

In [1]:
import numpy as np

In [76]:
hun = np.linspace(0,100, 101).astype(int)  # baseline


Now for each scale I will allow only the values $$[0; 2* PI)$$

In [75]:
hun

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [126]:
scales = 7  # 2**10 

In [127]:
scaled = np.stack([ np.divide(hun, 2**i) for i in range(scales)])

In [132]:
scaled2 = np.stack([ np.remainder(hun, 2**i) for i in range(scales)])

In [134]:
scaled3 = np.stack([ np.pi * hun / 2**i for i in range(scales)])

In [139]:
scaled4 = []
for i in reversed(range(1, scaled3.shape[0])):
    scaled4.append(scaled3[i]-scaled3[i-1])
scaled4 = np.stack(scaled4)

In [142]:
sincoded3 = np.sin(scaled3)
sincoded4 = np.sin(scaled4)

In [143]:
sindec3 = np.arcsin(sincoded3)
sindec4 = np.arcsin(sincoded4)

In [144]:
dec3 = []
for i in range((sindec3.shape)[0]):
    dec3.append(sindec3[i] * 2**i )

dec4 = []
for i in range((sindec4.shape)[0]):
    dec4.append(sindec4[i] * 2**i )

fdec3 = np.sum(dec3,axis=0).astype(int)
fdec4 = np.sum(dec4,axis=0).astype(int)

In [145]:
fdec3

array([   0,   18,   31,   37,   50,   56,   56,   62,   75,   81,   81,
         75,   75,   81,   81,   87,  100,  106,  106,  100,  100,   94,
         81,   75,   75,   81,   81,   75,   75,   81,   81,   87,  100,
        106,  106,  100,  100,   94,   81,   75,   75,   69,   56,   37,
         25,   18,    6,    0,    0,    6,    6,    0,    0,   -6,  -18,
        -25,  -25,  -18,  -18,  -25,  -25,  -18,  -18,  -12,    0,   12,
         18,   18,   25,   25,   18,   18,   25,   25,   18,    6,    0,
          0,   -6,   -6,    0,    0,   -6,  -18,  -25,  -37,  -56,  -69,
        -75,  -75,  -81,  -94, -100, -100, -106, -106, -100,  -87,  -81,
        -81,  -75])

In [146]:
fdec4

array([  0, -67, -33,  25, -16, -52,  12,  52,  -8, -67, -26,  40,   6,
       -33,  26,  61,  -3, -68, -33,  27, -12, -46,  20,  62,   3, -56,
       -16,  48,  13, -27,  31,  65,  -1, -68, -34,  25, -16, -51,  14,
        54,  -5, -64, -22,  44,  10, -29,  31,  67,   2, -62, -27,  32,
        -7, -41,  25,  66,   7, -53, -13,  51,  16, -25,  33,  66,   0,
       -66, -33,  25, -16, -51,  13,  53,  -7, -66, -25,  41,   7, -32,
        27,  62,  -2, -67, -31,  29, -10, -44,  22,  64,   5, -54, -14,
        51,  16, -25,  34,  68,   1, -65, -31,  27, -13])

In [129]:
scaled.shape

(7, 101)

In [130]:
[2**i for i in range(scales)]

[1, 2, 4, 8, 16, 32, 64]

In [112]:
sincoded = np.sin(scaled)

In [113]:
sincoded

array([[ 0.        ,  0.84147098,  0.90929743, ..., -0.57338187,
        -0.99920683, -0.50636564],
       [ 0.        ,  0.47942554,  0.84147098, ..., -0.95375265,
        -0.69288495, -0.26237485],
       [ 0.        ,  0.24740396,  0.47942554, ..., -0.59135753,
        -0.37346475, -0.13235175],
       ...,
       [ 0.        ,  0.00781242,  0.01562436, ...,  0.69298773,
         0.69859894,  0.70416751],
       [ 0.        ,  0.00390624,  0.00781242, ...,  0.37353087,
         0.37715152,  0.38076641],
       [ 0.        ,  0.00195312,  0.00390624, ...,  0.19023965,
         0.19215674,  0.1940731 ]])

In [114]:
sindec = np.arcsin(sincoded)

In [115]:
sindec

array([[ 0.        ,  1.        ,  1.14159265, ..., -0.61062774,
        -1.53096491, -0.53096491],
       [ 0.        ,  0.5       ,  1.        , ..., -1.26548246,
        -0.76548246, -0.26548246],
       [ 0.        ,  0.25      ,  0.5       , ..., -0.63274123,
        -0.38274123, -0.13274123],
       ...,
       [ 0.        ,  0.0078125 ,  0.015625  , ...,  0.765625  ,
         0.7734375 ,  0.78125   ],
       [ 0.        ,  0.00390625,  0.0078125 , ...,  0.3828125 ,
         0.38671875,  0.390625  ],
       [ 0.        ,  0.00195312,  0.00390625, ...,  0.19140625,
         0.19335938,  0.1953125 ]])

In [117]:
list(range((sindec.shape)[0]))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [118]:
dec = []
for i in range((sindec.shape)[0]):
    dec.append(sindec[i] * 2**i )

dec = np.stack(dec)

In [119]:
np.sum(dec,axis=0).astype(int)

array([  0,  10,  19,  27,  33,  40,  48,  54,  60,  64,  69,  75,  83,
        90,  96, 100, 104, 106, 109, 114, 120, 124, 128, 134, 141, 149,
       156, 161, 165, 167, 170, 174, 177, 179, 179, 179, 181, 185, 190,
       196, 200, 204, 206, 209, 213, 219, 224, 228, 234, 241, 249, 255,
       261, 265, 268, 270, 274, 277, 279, 279, 280, 282, 285, 289, 291,
       292, 292, 290, 289, 289, 290, 292, 292, 293, 296, 300, 305, 311,
       315, 318, 320, 324, 327, 329, 329, 330, 332, 335, 339, 345, 350,
       354, 356, 359, 363, 368, 374, 378, 383, 389, 397])

In [105]:
hun

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [66]:
sc = 1. / scales.transpose()

In [67]:
# np.remainder(hun, scales.transpose()).astype(int).transpose().tolist()

In [68]:
v = (sc * hun ).astype(int)

In [16]:
np.sin(3.*np.pi/2.)

-1.0

In [ ]:
hun * 